### ISSUE TITLE
when i use input to set entries and change css name in manualChunks, inject failed

### ISSUE THREAD

**Issue by eveforest** [emosheeep/fe-tools#11]
when i use input to set entries and change css name in manualChunks, inject failed. and got:
`/* empty css                      */`

manualChunks cchange source.css: index*.css  to XxxComponent.css

this failed:
```typescript
input: {
  'index':'ui/index.ts'
},
output: {
  manualChunks: (id) => {
              if (id.includes('.css'))
               return pipe(
                  split('/'),
                  last,
                  split('.css'),
                  head
                )(id) as string
  }
  entryFileNames: (chunkInfo) => chunkInfo.name === 'index' ? '[format]/index.js' : '[format]/[name]/index.js',
  chunkFileNames: '[format]/[name]/index.js',
  assetFileNames: '[ext]/[name].[ext]',
}
``` 

this worked:
```typescript
input: {
  'index':'ui/index.ts'
},
output: {
  manualChunks: (id) => {
    //           if (id.includes('.css'))
    //             return pipe(
    //               split('/'),
  //                 last,
     //              split('.css'),
   //                head
 //               )(id) as string
  }
  entryFileNames: (chunkInfo) => chunkInfo.name === 'index' ? '[format]/index.js' : '[format]/[name]/index.js',
  chunkFileNames: '[format]/[name]/index.js',
  assetFileNames: '[ext]/[name].[ext]',
}
```

**Comment by emosheeep** [comment]
This plugin totally depend on `viteMetaData` property injected by vite in renderChunk hook, if there's no css was injected, may be it doesn't support this situation now.🤔

**Comment by emosheeep** [comment]
Or vite handle this in the next hook(generateBundle)，we can't inject in this hook， because it breaks the sourcemap.

**Comment by eveforest** [comment]
so there is no way to fix this problem ? anyway ，without named css file work fine also acceptable.just a try.

**Comment by emosheeep** [comment]
I've tried it at the beginning to inject css in generateBundle hook, I forget what made me give up diving deep, but i do fail.

**Comment by eveforest** [comment]
It doesn't matter, not a necessary issue.  i will close thiis issue later

**Comment by eveforest** [comment]
thanks for your focus on .

**Comment by emosheeep** [comment]
good night guys

**Comment by eveforest** [comment]
good night bro.
