### ISSUE TITLE
vite-plugin-lib-inject-css not working on SSR

### ISSUE THREAD

**Issue by pmrotule** [emosheeep/fe-tools#12]
We are currently migrating our Vue component library from Rollup to Vite. We gave a try to `vite-plugin-lib-inject-css` which is working like a charm for the client assets, but it doesn't work for the server assets (build with the `--ssr` flag). It seems like it adds an import statement for the css file even though it doesn't exist (no CSS is generated on SSR which is expected).

I created a reproduction: https://stackblitz.com/edit/vue3-vite-starter-f7mk9t?file=dist%2Fserver%2FMyButton.mjs

<img width="1386" alt="Screenshot 2023-09-07 at 13 03 07" src="https://github.com/emosheeep/fe-tools/assets/10983258/4119167f-0c7a-42cd-9bab-356098bfd4b2">

Of course, this breaks our SSR app that complains about the missing CSS files. One way to fix it would have been by using the SSR manifest generate with the `--ssrManifest` on client build, but it doesn't seem to work properly as the CSS file is sometimes missing. As you can see in my reproduction project, the entry `HelloWorld` doesn't have anything listed in the manifest:

<img width="701" alt="image" src="https://github.com/emosheeep/fe-tools/assets/10983258/c7d5a845-3864-4b46-a93e-1d0c392e5c3c">

So maybe `vite-plugin-lib-inject-css` could generate its own manifest and use it on SSR (e.g. by adding an option `ssrManifestOutDir: '/absolute/path/to/dist/client'` to retrieve the manifest on server build).

Can I suggest a solution by contributing a pull request? We are blocked by this issue so it's in our best interest to make it happen as soon as possible.

Thanks for the plugin by the way, it's a really nice solution to handle the CSS files 🙌

**Comment by emosheeep** [comment]
Of course sure, I'm trapped in my work and have no time to handle this for now, It would be fine if you have interest on it🎉

**Comment by emosheeep** [comment]
and I don't have much experience on ssr, i may need some days researching on it👀

**Comment by emosheeep** [comment]
vite-plugin-lib-inject-css (1.3.0) is published, you can have a try.

**Comment by pmrotule** [comment]
It works as expected. Thank you 🙌
