### ISSUE TITLE
Consider @import url()

### ISSUE THREAD

**Issue by emersonbottero** [emosheeep/fe-tools#14]
Fantastic plugin... 

I use this plugin in a library but the styles are external.... They are scss and your library still works.

If you can think of a workaround I can do a replace in all files for example.

Thanks.

**Comment by emosheeep** [comment]
Did you mean you don't expect the styles to be referenced in Chunk file？ This plugin is made for this..🤔

**Comment by emersonbottero** [comment]
I want them to.
But the path inside url is relative but the plugin never changes them... 
So the styles on each chuck can't find the fonts in this case and we get warnings that they couldn't be found.

**Comment by emosheeep** [comment]
Could you please provide me a minimal reproduction so I can take a look
