### ISSUE TITLE
[Error] Cannot build Storybook with vite-plugin-lib-inject-css: TypeError "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by AliVP97** [emosheeep/fe-tools#17]
I'm encountering an error when attempting to build static Storybook files using `npm run build-storybook`. The error message is:

```
TypeError: Cannot convert undefined or null to object
  at Function.values (<anonymous>)
  at configResolved (file:///C:/Github/infrastructure/node_modules/vite-plugin-dts/dist/index.mjs:743:100)
  ...
```

**Relevant Dependencies:**

```json
{
  "vite": "^4.2.0",
  "storybook": "^7.0.23",
  "vite-plugin-lib-inject-css": "^1.3.0"
}
```

**Additional Information:**

- The build process successfully ran when `lib-inject-css` is disabled

**I'd appreciate any guidance on how to resolve this issue.**

**Thank you for your time and attention to this matter.**

**Comment by emosheeep** [comment]
Duplicated https://github.com/emosheeep/vite-plugin-lib-inject-css/issues/15, 2.0.0-beta.0 has published, you can have a try.

**Comment by emosheeep** [comment]
@receter I noticed that you wrote the solution of `How to use this plugin with Storybook` [here](https://dev.to/receter/how-to-create-a-react-component-library-using-vites-library-mode-4lma), which is actually relevant about this issue, and I fixed it a few days ago, may be you can update something when you're free. 😄

**Comment by receter** [comment]
@emosheeep Thanks for letting me know! I have tested version 2 and the issue is solved. I have updated the storybook branch and my article.
