### ISSUE TITLE
issue while building

### ISSUE THREAD

**Issue by dberardo-com** [emosheeep/fe-tools#20]
i get this error while building ...

error during build:
RollupError: Plugin error - Unable to get file name for unknown file "OKEml5WQ".

sounds familiar ?

**Comment by emosheeep** [comment]
Could you please provide a minimal reproduction？

**Comment by dberardo-com** [comment]
i am not sure what it could depend on ... i am using vite 5 and other plugins:

"@vitejs/plugin-react": "^4.2.0",
"vite": "^5.0.0",
"vite-plugin-ejs": "^1.7.0",
"vite-plugin-entry-shaking": "^0.3.3",
"vite-plugin-mkcert": "^1.17.1",

cant really say for now whats wrong, but this error might be happening because the plugin is parsing the entrypoint file index.js ? no sure.

**Comment by emosheeep** [comment]
no，this plugin only depends on vite not a certain project

**Comment by dberardo-com** [comment]
sure, i was referring to my project, i have these other plugins installed, not sure if those might conflict
