### ISSUE TITLE
Any way to skip the CSS of an external dependency?

### ISSUE THREAD

**Issue by sky0matic** [emosheeep/fe-tools#25]
Hi there,

Trying to make a Vue library that uses Vuetify.
The issue is that when I `export` a Vue component that uses a component of `vuetify`, it exports the style of vuetify needed for it.

I don't really want this as I know that app using my library will be using `vuetify` (even marked it as a `peerDependency` in my `package.json`).

What I want is the custom CSS that this component could have.

Thanks in advance for your answer

**Comment by emosheeep** [comment]
Could you please give me a minimal reproduction，I can't totally understand.

**Comment by sky0matic** [comment]
Here you go : 

1. Go to https://codesandbox.io/p/devbox/affectionate-cdn-lrk76z
2. Check the `dist/assets/HelloWorld.css`.
3. Notice how it has all the CSS for `v-*` (like `v-btn`) which comes from Vuetify which I don't want in my library, I would only want to have the `read-the-docs` one.

If you want to build it yourself for testing purpose, just : 
1. Clone the sandbox
2. `npm run build`

Vuetify is a `peerDependencies`, the apps using the library will already have it and have imported vuetify's css

**Comment by sky0matic** [comment]
Oh well.. I think I found the issue.

In `vite.config.ts`, I replaced the `build.rollupOptions.external` to `[/node_modules/]` and it looks like it's working now..

Sorry for the inconvenience

**Comment by sky0matic** [comment]
Oh well.. I think I found the issue.

In `vite.config.ts`, I replaced the `build.rollupOptions.external` to `[/node_modules/]` and it looks like it's working now..

Sorry for the inconvenience
