### ISSUE TITLE
vben5使用后存在兼容性问题无法启动项目

### ISSUE THREAD

**Issue by Rascal-Coder** [emosheeep/fe-tools#27]
<img width="777" alt="b3caf92a89a112741f6e7912b065e7b" src="https://github.com/user-attachments/assets/8dea48cb-e12a-41b0-9a81-48017c4e43a6">

**Comment by Rascal-Coder** [comment]
@ast-grep/napi这个版本问题

**Comment by emosheeep** [comment]
具体啥问题，没 get 到，要升级吗还是

**Comment by Rascal-Coder** [comment]
不知道啥原因就是我现在是vben5，然后vben5使用了🐏这个css注入插件，这个插件中有一个@ast-grep/napi依赖，pnpm@9.12.3下载的依赖在pnpm dev时会无法找到特殊模块，我大致推测是这个@ast-grep/napi win系统兼容 问题

**Comment by Rascal-Coder** [comment]
我测试了注释掉[vite-plugin-lib-inject-css]的使用就恢复了正常，您可以测试一下

**Comment by emosheeep** [comment]
你尝试 pnpm overrides 全局覆盖一下 @ast-grep/napi 到最新版，如果没问题的话，我可以 patch 一下升级个版本，如果有问题，就需要给 @ast-grep/napi 提 issue

**Comment by Rascal-Coder** [comment]
好的我试试谢谢您了

**Comment by Rascal-Coder** [comment]
![image](https://github.com/user-attachments/assets/37971c90-8320-431e-9cce-5c99e10f1da2)
wo'shi'zhe我是这么写的，不知道是否正确如何查看是否覆盖成功呢？

**Comment by emosheeep** [comment]
pnpm why @ast-grep/napi -r

**Comment by Rascal-Coder** [comment]
谢谢我知道为什么出现问题了vben5admin中使用了circular-dependency-scanner这个库它也使用了 
circular-dependency-scanner 2.3.0
└── @ast-grep/napi 0.27.3

vite-plugin-lib-inject-css 2.1.1
└── @ast-grep/napi 0.22.6
导致冲突了谢谢您了
