### ISSUE TITLE
The plugin doesn't work when "preserveModules" option is enabled

### ISSUE THREAD

**Issue by xbzhang2020** [emosheeep/fe-tools#29]
When `vite.config.ts` is as follows：
<img width="537" alt="截屏2024-12-26 15 10 13" src="https://github.com/user-attachments/assets/498376b1-ed00-4cef-a4fb-9339be437e54" />

There is no css injected in js bundles after build.
<img width="994" alt="截屏2024-12-26 15 13 30" src="https://github.com/user-attachments/assets/6b40acff-f21c-4f00-b8ec-258c21e0555f" />

But if I set `build.rollupOptions.output.preserveModules` to false, it will work again.
<img width="1015" alt="截屏2024-12-26 15 15 59" src="https://github.com/user-attachments/assets/8a1603a8-9983-43a3-9a83-94e96bb9251c" />

**Comment by emosheeep** [comment]
Please refer to https://github.com/emosheeep/vite-plugin-lib-inject-css?tab=readme-ov-file#why-does-style-code-injection-fail

**Comment by xbzhang2020** [comment]
I got it. Thanks.

**Comment by xbzhang2020** [comment]
Wait! I resolved it. 

The build result with `build.rollupOptions.output.preserveModules` is as follows.

<img width="1054" alt="截屏2024-12-26 18 11 55" src="https://github.com/user-attachments/assets/dae4f8b8-0627-4c03-af98-ce78aba204fa" />

Here is my `vite.config.ts` . Maybe you can have a try in the [examle](https://github.com/emosheeep/vite-plugin-lib-inject-css/tree/master/example).
```
import type { Plugin } from 'vite';
import { dirname, relative } from 'node:path';
import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';
// import { libInjectCss } from '../src/index';

function libInjectCss(): Plugin {
  return {
    name: 'vite:lib-inject-css',
    generateBundle(_, bundle) {
      for (const chunk of Object.values(bundle)) {
        if (chunk.type !== 'chunk' || !chunk.viteMetadata?.importedCss.size) {
          continue;
        }

        const { importedCss } = chunk.viteMetadata;
        const cssFiles = Array.from(importedCss).map((item) => {
          let cssFilePath = relative(dirname(chunk.fileName), item);
          if (!cssFilePath.startsWith('.')) {
            cssFilePath = `./${cssFilePath}`;
          }
          return `import '${cssFilePath}';`;
        });
        chunk.code = `${cssFiles.join('\n')}\n${chunk.code}`;
      }
    },
    enforce: 'post',
  };
}

export default defineConfig({
  plugins: [vue(), libInjectCss()],
  build: {
    lib: {
      formats: ['es'],
      entry: ['src/demo1/index.ts', 'src/demo2/index.ts'],
    },
    cssCodeSplit: true,
    rollupOptions: {
      external: ['vue'],
      output: {
        preserveModules: true,
      },
    },
  },
});
```

**Comment by emosheeep** [comment]
🤔Is it because the new version of vite fixes this problem? I will try it later

**Comment by emosheeep** [comment]
```js
{
  entry: [
    // 'src/index.ts',
    // 'src/common.ts',
    'src/demo1/index.ts',
    'src/demo2/index.ts',
  ],
}
```

**Comment by emosheeep** [comment]
Seems you just removed two lines that I commented, I don't know how it works, maybe `preserveModules` option can be a warning which doesn’t block the injection logic. How it performs depends on vite, as the plugin relies on viteMetaData.

```js
export default defineConfig({
  build: {
    lib: {
      entry: [
        // 'src/index.ts',
        // 'src/common.ts',
        'src/demo1/index.ts',
        'src/demo2/index.ts',
      ],
    },
    rollupOptions: {
      output: {
        preserveModules: true,
      },
    },
  },
});
```

**Comment by xbzhang2020** [comment]
But it also works when I add the four entries. 

<img width="1375" alt="截屏2024-12-27 09 49 55" src="https://github.com/user-attachments/assets/ffa9b462-23f7-4874-9892-39a0ba4f310b" />


```
// vite.config.ts
export default defineConfig({
  plugins: [vue(), libInjectCss()],
  build: {
    lib: {
      formats: ['es'],
      entry: [
        'src/index.ts',
        'src/common.ts',
        'src/demo1/index.ts',
        'src/demo2/index.ts',
      ],
    },
    cssCodeSplit: true,
    rollupOptions: {
      external: ['vue'],
      output: {
        preserveModules: true,
      },
    },
  },
});
```

**Comment by emosheeep** [comment]
What is the version of the Vite you used ？

**Comment by xbzhang2020** [comment]
vite 5.4.10

**Comment by emosheeep** [comment]
Wow, I got it, there was a historical problem has been fixed accidentally by this commit https://github.com/emosheeep/vite-plugin-lib-inject-css/commit/1841f4421b24a2817f7e80640cd834b5b4411cfb, maybe I should remove the restrictions and then support code injection when `preserveModules` option is enabled.

**Comment by xbzhang2020** [comment]
👍。哈哈哈，看起来是调用时机的问题，应该在 generateBundle 钩子中调用注入代码。
