### ISSUE TITLE
Check for deprecated rollupOptions.preserveModules

### ISSUE THREAD

**Issue by receter** [emosheeep/fe-tools#5]
> When rollupOptions.output.preserveModules is true, the association between a chunk and the css it referenced will lose for some reason, in which case style injection will be skipped.

It is possible to bypass this security check if the deprecated option `rollupOptions.preserveModules` is used.

**Comment by emosheeep** [comment]
So the problem is that you want to use preserveModules with this plugin？
This plugin depends on viteMetaData property injected by vite on each chunk file, I used to run with preserveModule, but as the tips saying, when it is enabled, i can't get the associations because viteMetaData is empty in renderChunk hook.  I can get it in next hook generateChunk but if i modify file content, the sourcemap will break.  I haven't found a good resolution yet

**Comment by receter** [comment]
That would be great, but I read that this might be more complicated and definitely is another issue/feature request.

I just opened this because if it leads to unexpected behaviour, it might be good to show the warning in both cases. I can create a pull request if you want me to.

**Comment by emosheeep** [comment]
well, i got it, i'll appreciate if you could make a PR

**Comment by emosheeep** [comment]
Oh I realized that I misunderstood the issue, i just thought you want to use preserveMoudle with this plugin😂

> To split up the css I tried `preserveModules` with `cssCodeSplit` but this just leads to a bunch of unassignable css files (https://github.com/vitejs/vite/issues/8057).

Now I know, what did you say is that you use preserveModules and cssCodeSplit independently, and you compared it with my plugin and choose the latter😄

**Comment by receter** [comment]
#6

**Comment by receter** [comment]
Yes.

But nevertheless, if your plugin would work with preserveModules it would be ideal for my use case.

I wonder if it is just a vite issue that viteMetaData is empty when preserveModules is true.

**Comment by emosheeep** [comment]
I dived into the vite's implementation and  found vite collect the associations among the chunks by itself,I don't think of it as a bug. Maybe we need to implement these logic by ourselves like vite. But for now I think preserveModules is not necessary for us, indeed, the users who use your library usually don't care about how your dist directory structure looks like.
