### ISSUE TITLE
Incorrect css insertion path on Windows

### ISSUE THREAD

**Issue by teleskop150750** [emosheeep/fe-tools#9]
Incorrect css insertion path on Windows

![image](https://github.com/emosheeep/fe-tools/assets/62594983/5919c144-5f12-46e1-86bd-fa2b3b3c7a6f)

Perhaps the solution is to replace the backslash

![image](https://github.com/emosheeep/fe-tools/assets/62594983/90a5a17e-66a3-4430-a4f5-cb3ac09f8911)

![image](https://github.com/emosheeep/fe-tools/assets/62594983/b6eb30af-31ec-4884-9e8b-dcf4518dc360)

![image](https://github.com/emosheeep/fe-tools/assets/62594983/c4d96c5e-e6b9-40c7-b91e-216fd61b9242)

**Comment by eveforest** [comment]
same problem i met too

**Comment by emosheeep** [comment]
Okay, I'll fix it later, cross-platform path handling does make me crazy, anyone who knows some tool libraries? I can't always deal one by one, that is inefficient.

**Comment by teleskop150750** [comment]
> Okay, I'll fix it later, cross-platform path handling does make me crazy, anyone who knows some tool libraries? I can't always deal one by one, that is inefficient.

[normalizePath](https://github.com/sapphi-red/vite-plugin-static-copy#usage)
